# Training Models

In [1]:
from model_trainer import ModelTrainer

## Large

In [2]:
trainer = ModelTrainer(
    base_model="google-bert/bert-large-uncased",
    dataset="guten_sentiment.csv",
    num_classes=10,
    max_len=256,
    output_dir="./bert_ordinal/large",
    seed=1111
)

In [3]:
df = trainer.read_validate_data()
print(df.head())

Number of observations: 10889

Label distribution:
label
1      239
2      800
3     1436
4      821
5     4519
6      960
7      637
8      923
9      474
10      80
Name: count, dtype: int64
                                                text  label
0             In a moment they breathed more freely.      7
1  “I’m in favor of the eats part and that withou...      8
2  They even put preventer stays on the masts and...      5
3  “They’re merely telling one another what a nic...      7
4  It looks to me as if we’d never have another c...      8

In [4]:
trainer.set_training_parameters()

Split sizes:
Train: 8711
Validation: 1089
Test: 1089

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=1111,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=100,
eval_strategy=steps,
eval_use_gather_object=False,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./bert_ordinal/large/runs/Oct11_12-12-17_artem-MS-7C52,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=100,
logging_strategy=steps,
lr_scheduler_kwargs={},
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=mae,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=3,
optim=adamw_torch_fused,
optim_args=None,
optim_target_modules=None,
output_dir=./bert_ordinal/large,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=16,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=100,
save_strategy=steps,
save_total_limit=6,
seed=1111,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [5]:
trainer.tokenize_dataset()

Map:   0%|          | 0/8711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8711
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }))

In [6]:
trainer.train()

Some weights of BertForOrdinalRegression were not initialized from the model checkpoint at google-bert/bert-large-uncased and are newly initialized: ['first_threshold', 'sentiment_score.bias', 'sentiment_score.weight', 'threshold_deltas']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

early stopping required metric_for_best_model, but did not find eval_mae so early stopping is disabled

Test results:
test_loss: 7.026209163754326e+30
test_mae: 0.8375439047813416
test_rmse: 1.196198278602493
test_accuracy: 0.46097337006427913
test_within_1: 0.8135904499540864
test_quadratic_kappa: 0.7458796944429511
test_spearman: 0.7634938263273856
test_runtime: 3.2592
test_samples_per_second: 334.129
test_steps_per_second: 10.739
epoch: 3.0

TrainOutput(global_step=1635, training_loss=7.024805520282699e+30, metrics={'train_runtime': 499.2583, 'train_samples_per_second': 52.344, 'train_steps_per_second': 3.275, 'total_flos': 4161445477853616.0, 'train_loss': 7.024805520282699e+30, 'epoch': 3.0})

In [ ]:
results = trainer.test_results

print("Test MAE:", results["test_mae"])
print("Test RMSE:", results["test_rmse"])
print("Test Accuracy:", results["test_accuracy"])

Test MAE: 0.8375439047813416
Test RMSE: 1.196198278602493
Test Accuracy: 0.46097337006427913

In [8]:
checkpoints = trainer.evaluate_interim_models()
print(checkpoints)

trainer.save_best_models(
    best_model_dir="./models/bert_ordinal_large_final"
)

                           checkpoint  step  is_best  validation_loss  \
0  bert_ordinal/large/checkpoint-1200  1200    False     7.065164e+30
1  bert_ordinal/large/checkpoint-1300  1300    False     7.065119e+30
2  bert_ordinal/large/checkpoint-1400  1400    False     7.065074e+30
3  bert_ordinal/large/checkpoint-1500  1500    False     7.065074e+30
4  bert_ordinal/large/checkpoint-1600  1600     True     7.065074e+30
5  bert_ordinal/large/checkpoint-1635  1635    False     7.065074e+30

   validation_model_preparation_time  validation_mae  validation_rmse  \
0                             0.0051        0.860364         1.217885
1                             0.0049        0.864987         1.220383
2                             0.0048        0.860437         1.224751
3                             0.0049        0.846847         1.212655
4                             0.0049        0.846662         1.209902
5                             0.0036        0.846909         1.210526

   validation_accuracy  validation_within_1  validation_quadratic_kappa  \
0             0.449954             0.803489                    0.718647
1             0.454545             0.801653                    0.716230
2             0.454545             0.808999                    0.735359
3             0.472911             0.808999                    0.735495
4             0.467401             0.809917                    0.729687
5             0.468320             0.810836                    0.731911

   validation_spearman  validation_runtime  validation_samples_per_second  \
0             0.741193              2.8906                        376.733
1             0.741089              2.9383                        370.629
2             0.744661              2.9222                        372.670
3             0.744747              2.9167                        373.367
4             0.744130              2.8855                        377.406
5             0.744510              2.8792                        378.229

   validation_steps_per_second
0                       12.108
1                       11.912
2                       11.977
3                       12.000
4                       12.130
5                       12.156

Model saved to: models/bert_ordinal_large_final

PosixPath('models/bert_ordinal_large_final')

## Base

In [2]:
trainer = ModelTrainer(
    base_model="google-bert/bert-base-uncased",
    dataset="guten_sentiment.csv",
    num_classes=10,
    max_len=256,
    output_dir="./bert_ordinal/base",
    seed=1111
)

In [3]:
df = trainer.read_validate_data()
print(df.head())
trainer.tokenize_dataset()

Number of observations: 10889

Label distribution:
label
1      239
2      800
3     1436
4      821
5     4519
6      960
7      637
8      923
9      474
10      80
Name: count, dtype: int64
                                                text  label
0             In a moment they breathed more freely.      7
1  “I’m in favor of the eats part and that withou...      8
2  They even put preventer stays on the masts and...      5
3  “They’re merely telling one another what a nic...      7
4  It looks to me as if we’d never have another c...      8

Split sizes:
Train: 8711
Validation: 1089
Test: 1089

Map:   0%|          | 0/8711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8711
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }))

In [4]:
trainer.train()

Some weights of BertForOrdinalRegression were not initialized from the model checkpoint at google-bert/bert-base-uncased and are newly initialized: ['first_threshold', 'sentiment_score.bias', 'sentiment_score.weight', 'threshold_deltas']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

early stopping required metric_for_best_model, but did not find eval_mae so early stopping is disabled

Test results:
test_loss: 1.5415543211543839e+28
test_mae: 0.9594042897224426
test_rmse: 1.3123711113996128
test_accuracy: 0.40128558310376494
test_within_1: 0.7713498622589532
test_quadratic_kappa: 0.6801793277386919
test_spearman: 0.7109794589869166
test_runtime: 1.093
test_samples_per_second: 996.307
test_steps_per_second: 32.021
epoch: 1.834862385321101

TrainOutput(global_step=1000, training_loss=1.6132025971709482e+28, metrics={'train_runtime': 100.2943, 'train_samples_per_second': 260.563, 'train_steps_per_second': 16.302, 'total_flos': 719905028755980.0, 'train_loss': 1.6132025971709482e+28, 'epoch': 1.834862385321101})

In [5]:
# Evaluate
results = trainer.test_results

print("Test MAE:", results["test_mae"])
print("Test RMSE:", results["test_rmse"])
print("Test Accuracy:", results["test_accuracy"])

Test MAE: 0.9594042897224426
Test RMSE: 1.3123711113996128
Test Accuracy: 0.40128558310376494

In [6]:
# Evaluate intermediate checkpoints
checkpoints = trainer.evaluate_interim_models()
print(checkpoints)

# Save best model
trainer.save_best_models(
    best_model_dir="./models/bert_ordinal_base_final"
)

                          checkpoint  step  is_best  validation_loss  \
0   bert_ordinal/base/checkpoint-500   500    False     1.541574e+28
1   bert_ordinal/base/checkpoint-600   600     True     1.541554e+28
2   bert_ordinal/base/checkpoint-700   700    False     1.541534e+28
3   bert_ordinal/base/checkpoint-800   800    False     1.541515e+28
4   bert_ordinal/base/checkpoint-900   900    False     1.541495e+28
5  bert_ordinal/base/checkpoint-1000  1000    False     1.541482e+28

   validation_model_preparation_time  validation_mae  validation_rmse  \
0                             0.0026        1.028163         1.397926
1                             0.0028        0.970651         1.331973
2                             0.0026        1.080510         1.427216
3                             0.0019        1.006825         1.367417
4                             0.0020        0.975874         1.362695
5                             0.0020        0.972772         1.360931

   validation_accuracy  validation_within_1  validation_quadratic_kappa  \
0             0.378329             0.759412                    0.652658
1             0.409550             0.772268                    0.674372
2             0.344353             0.731864                    0.599850
3             0.381084             0.759412                    0.650156
4             0.415060             0.763085                    0.642519
5             0.414141             0.752066                    0.643861

   validation_spearman  validation_runtime  validation_samples_per_second  \
0             0.668066              1.0074                       1080.972
1             0.686737              1.0139                       1074.084
2             0.682789              0.9748                       1117.145
3             0.690933              0.9513                       1144.727
4             0.674370              0.9612                       1132.959
5             0.686657              0.9630                       1130.886

   validation_steps_per_second
0                       34.742
1                       34.521
2                       35.905
3                       36.791
4                       36.413
5                       36.346

Model saved to: models/bert_ordinal_base_final

PosixPath('models/bert_ordinal_base_final')

## Medium

In [ ]:
trainer = ModelTrainer(
    base_model="google/bert_uncased_L-8_H-512_A-8",
    dataset="guten_sentiment.csv",
    num_classes=10,
    max_len=128,
    output_dir="./bert_ordinal/medium",
    seed=1111
)

In [3]:
df = trainer.read_validate_data()
print(df.head())
trainer.tokenize_dataset()

Number of observations: 10889

Label distribution:
label
1      239
2      800
3     1436
4      821
5     4519
6      960
7      637
8      923
9      474
10      80
Name: count, dtype: int64
                                                text  label
0             In a moment they breathed more freely.      7
1  “I’m in favor of the eats part and that withou...      8
2  They even put preventer stays on the masts and...      5
3  “They’re merely telling one another what a nic...      7
4  It looks to me as if we’d never have another c...      8

Split sizes:
Train: 8711
Validation: 1089
Test: 1089

Map:   0%|          | 0/8711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8711
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }))

In [4]:
trainer.train()

Some weights of BertForOrdinalRegression were not initialized from the model checkpoint at google/bert_uncased_L-8_H-512_A-8 and are newly initialized: ['first_threshold', 'sentiment_score.bias', 'sentiment_score.weight', 'threshold_deltas']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

early stopping required metric_for_best_model, but did not find eval_mae so early stopping is disabled

Test results:
test_loss: 0.32726791501045227
test_mae: 1.078230857849121
test_rmse: 1.5046135366291054
test_accuracy: 0.371900826446281
test_within_1: 0.7419651056014692
test_quadratic_kappa: 0.5929324849108273
test_spearman: 0.566537606093174
test_runtime: 0.3951
test_samples_per_second: 2756.29
test_steps_per_second: 88.586
epoch: 2.7522935779816513

TrainOutput(global_step=1500, training_loss=0.323000181833903, metrics={'train_runtime': 62.5537, 'train_samples_per_second': 417.769, 'train_steps_per_second': 26.138, 'total_flos': 302581209192732.0, 'train_loss': 0.323000181833903, 'epoch': 2.7522935779816513})

In [7]:
# Evaluate
results = trainer.test_results

print("Test MAE:", results["test_mae"])
print("Test RMSE:", results["test_rmse"])
print("Test Accuracy:", results["test_accuracy"])

Test MAE: 1.078230857849121
Test RMSE: 1.5046135366291054
Test Accuracy: 0.371900826446281

In [8]:
# Evaluate intermediate checkpoints
checkpoints = trainer.evaluate_interim_models()
print(checkpoints)

# Save best model
trainer.save_best_models(
    best_model_dir="./models/bert_ordinal_medium_final"
)

                            checkpoint  step  is_best  validation_loss  \
0  bert_ordinal/medium/checkpoint-1000  1000    False         0.324039
1  bert_ordinal/medium/checkpoint-1100  1100     True         0.315078
2  bert_ordinal/medium/checkpoint-1200  1200    False         0.317722
3  bert_ordinal/medium/checkpoint-1300  1300    False         0.316571
4  bert_ordinal/medium/checkpoint-1400  1400    False         0.318709
5  bert_ordinal/medium/checkpoint-1500  1500    False         0.318144

   validation_model_preparation_time  validation_mae  validation_rmse  \
0                             0.0013        1.067428         1.488262
1                             0.0014        1.012187         1.415865
2                             0.0014        1.025011         1.436241
3                             0.0013        1.014753         1.428036
4                             0.0013        1.017320         1.441007
5                             0.0013        1.014738         1.437910

   validation_accuracy  validation_within_1  validation_quadratic_kappa  \
0             0.393939             0.733701                    0.600614
1             0.403122             0.757576                    0.625916
2             0.411387             0.746556                    0.639143
3             0.407713             0.750230                    0.635562
4             0.410468             0.752066                    0.643101
5             0.414141             0.757576                    0.644416

   validation_spearman  validation_runtime  validation_samples_per_second  \
0             0.598391              0.3924                       2775.238
1             0.613887              0.3901                       2791.921
2             0.616074              0.3753                       2901.427
3             0.619025              0.3818                       2852.356
4             0.617967              0.3831                       2842.950
5             0.618834              0.3781                       2879.862

   validation_steps_per_second
0                       89.195
1                       89.731
2                       93.251
3                       91.674
4                       91.371
5                       92.558

Model saved to: models/bert_ordinal_medium_final

PosixPath('models/bert_ordinal_medium_final')

## Small

In [9]:
trainer = ModelTrainer(
    base_model="google/bert_uncased_L-4_H-512_A-8",
    dataset="guten_sentiment.csv",
    num_classes=10,
    max_len=128,
    output_dir="./bert_ordinal/medium",
    seed=1111
)

In [10]:
df = trainer.read_validate_data()
print(df.head())
trainer.tokenize_dataset()

Number of observations: 10889

Label distribution:
label
1      239
2      800
3     1436
4      821
5     4519
6      960
7      637
8      923
9      474
10      80
Name: count, dtype: int64
                                                text  label
0             In a moment they breathed more freely.      7
1  “I’m in favor of the eats part and that withou...      8
2  They even put preventer stays on the masts and...      5
3  “They’re merely telling one another what a nic...      7
4  It looks to me as if we’d never have another c...      8

Split sizes:
Train: 8711
Validation: 1089
Test: 1089

config.json:   0%|          | 0.00/383 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/8711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8711
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }))

In [11]:
trainer.train()

pytorch_model.bin:   0%|          | 0.00/116M [00:00<?, ?B/s]

Some weights of BertForOrdinalRegression were not initialized from the model checkpoint at google/bert_uncased_L-4_H-512_A-8 and are newly initialized: ['first_threshold', 'sentiment_score.bias', 'sentiment_score.weight', 'threshold_deltas']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/116M [00:00<?, ?B/s]

early stopping required metric_for_best_model, but did not find eval_mae so early stopping is disabled

Test results:
test_loss: 3.717676877975464
test_mae: 1.142343521118164
test_rmse: 1.5463814766942252
test_accuracy: 0.35996326905417814
test_within_1: 0.6988062442607897
test_quadratic_kappa: 0.5290565808334495
test_spearman: 0.5316115798030101
test_runtime: 0.2439
test_samples_per_second: 4464.306
test_steps_per_second: 143.481
epoch: 2.7522935779816513

TrainOutput(global_step=1500, training_loss=3.7360804443359377, metrics={'train_runtime': 41.2167, 'train_samples_per_second': 634.04, 'train_steps_per_second': 39.668, 'total_flos': 152859134617884.0, 'train_loss': 3.7360804443359377, 'epoch': 2.7522935779816513})

In [12]:
# Evaluate
results = trainer.test_results

print("Test MAE:", results["test_mae"])
print("Test RMSE:", results["test_rmse"])
print("Test Accuracy:", results["test_accuracy"])

Test MAE: 1.142343521118164
Test RMSE: 1.5463814766942252
Test Accuracy: 0.35996326905417814

In [13]:
# Evaluate intermediate checkpoints
checkpoints = trainer.evaluate_interim_models()
print(checkpoints)

# Save best model
trainer.save_best_models(
    best_model_dir="./models/bert_ordinal_small_final"
)

                            checkpoint  step  is_best  validation_loss  \
0  bert_ordinal/medium/checkpoint-1000  1000    False         3.767451
1  bert_ordinal/medium/checkpoint-1100  1100     True         3.759080
2  bert_ordinal/medium/checkpoint-1200  1200    False         3.762287
3  bert_ordinal/medium/checkpoint-1300  1300    False         3.762727
4  bert_ordinal/medium/checkpoint-1400  1400    False         3.760925
5  bert_ordinal/medium/checkpoint-1500  1500    False         3.762222

   validation_model_preparation_time  validation_mae  validation_rmse  \
0                             0.0008        1.149301         1.518608
1                             0.0008        1.079466         1.461681
2                             0.0007        1.102493         1.486898
3                             0.0008        1.107097         1.490209
4                             0.0008        1.091551         1.481839
5                             0.0007        1.093807         1.488153

   validation_accuracy  validation_within_1  validation_quadratic_kappa  \
0             0.321396             0.707071                    0.552820
1             0.373737             0.708907                    0.556220
2             0.359045             0.724518                    0.608037
3             0.359963             0.726354                    0.595184
4             0.370064             0.730028                    0.618950
5             0.369146             0.729109                    0.604860

   validation_spearman  validation_runtime  validation_samples_per_second  \
0             0.586254              0.2404                       4529.949
1             0.588331              0.2397                       4542.364
2             0.591744              0.2421                       4497.725
3             0.590188              0.2382                       4571.712
4             0.590966              0.2458                       4430.169
5             0.591622              0.2393                       4549.961

   validation_steps_per_second
0                      145.591
1                      145.990
2                      144.555
3                      146.933
4                      142.384
5                      146.234

Model saved to: models/bert_ordinal_small_final

PosixPath('models/bert_ordinal_small_final')

## Mini

In [14]:
trainer = ModelTrainer(
    base_model="google/bert_uncased_L-4_H-256_A-4",
    dataset="guten_sentiment.csv",
    num_classes=10,
    max_len=128,
    output_dir="./bert_ordinal/medium",
    seed=1111
)

In [15]:
df = trainer.read_validate_data()
print(df.head())
trainer.tokenize_dataset()

Number of observations: 10889

Label distribution:
label
1      239
2      800
3     1436
4      821
5     4519
6      960
7      637
8      923
9      474
10      80
Name: count, dtype: int64
                                                text  label
0             In a moment they breathed more freely.      7
1  “I’m in favor of the eats part and that withou...      8
2  They even put preventer stays on the masts and...      5
3  “They’re merely telling one another what a nic...      7
4  It looks to me as if we’d never have another c...      8

Split sizes:
Train: 8711
Validation: 1089
Test: 1089

config.json:   0%|          | 0.00/383 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/8711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8711
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }))

In [16]:
trainer.train()

pytorch_model.bin:   0%|          | 0.00/45.1M [00:00<?, ?B/s]

Some weights of BertForOrdinalRegression were not initialized from the model checkpoint at google/bert_uncased_L-4_H-256_A-4 and are newly initialized: ['first_threshold', 'sentiment_score.bias', 'sentiment_score.weight', 'threshold_deltas']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

model.safetensors:   0%|          | 0.00/45.1M [00:00<?, ?B/s]

early stopping required metric_for_best_model, but did not find eval_mae so early stopping is disabled

Test results:
test_loss: 0.34424400329589844
test_mae: 1.2782011032104492
test_rmse: 1.6325666616712518
test_accuracy: 0.263544536271809
test_within_1: 0.6611570247933884
test_quadratic_kappa: 0.4450372082841968
test_spearman: 0.478666819695068
test_runtime: 0.2021
test_samples_per_second: 5389.387
test_steps_per_second: 173.213
epoch: 3.0

TrainOutput(global_step=1635, training_loss=0.368111013709952, metrics={'train_runtime': 29.9093, 'train_samples_per_second': 873.741, 'train_steps_per_second': 54.665, 'total_flos': 41866592104740.0, 'train_loss': 0.368111013709952, 'epoch': 3.0})

In [17]:
# Evaluate
results = trainer.test_results

print("Test MAE:", results["test_mae"])
print("Test RMSE:", results["test_rmse"])
print("Test Accuracy:", results["test_accuracy"])

Test MAE: 1.2782011032104492
Test RMSE: 1.6325666616712518
Test Accuracy: 0.263544536271809

In [18]:
# Evaluate intermediate checkpoints
checkpoints = trainer.evaluate_interim_models()
print(checkpoints)

# Save best model
trainer.save_best_models(
    best_model_dir="./models/bert_ordinal_mini_final"
)

                            checkpoint  step  is_best  validation_loss  \
0  bert_ordinal/medium/checkpoint-1200  1200    False         0.339015
1  bert_ordinal/medium/checkpoint-1300  1300    False         0.338482
2  bert_ordinal/medium/checkpoint-1400  1400    False         0.337828
3  bert_ordinal/medium/checkpoint-1500  1500    False         0.337359
4  bert_ordinal/medium/checkpoint-1600  1600     True         0.337287
5  bert_ordinal/medium/checkpoint-1635  1635    False         0.337238

   validation_model_preparation_time  validation_mae  validation_rmse  \
0                             0.0008        1.232047         1.593145
1                             0.0008        1.228187         1.590005
2                             0.0007        1.222571         1.585003
3                             0.0007        1.219939         1.581943
4                             0.0008        1.219151         1.581635
5                             0.0008        1.218602         1.581250

   validation_accuracy  validation_within_1  validation_quadratic_kappa  \
0             0.289256             0.672176                    0.446125
1             0.302112             0.679522                    0.458901
2             0.306703             0.687787                    0.473484
3             0.312213             0.684114                    0.474971
4             0.303949             0.685032                    0.472810
5             0.306703             0.685032                    0.473497

   validation_spearman  validation_runtime  validation_samples_per_second  \
0             0.536390              0.1943                       5605.005
1             0.534300              0.1934                       5630.542
2             0.537985              0.1939                       5614.892
3             0.538968              0.2256                       4826.245
4             0.539757              0.1990                       5472.404
5             0.539860              0.1909                       5704.890

   validation_steps_per_second
0                      180.142
1                      180.963
2                      180.460
3                      155.113
4                      175.881
5                      183.353

Model saved to: models/bert_ordinal_mini_final

PosixPath('models/bert_ordinal_mini_final')

## Tiny
Model	Hugging Face ID	Layers	Hidden size	Parameters
BERT-Large	google-bert/bert-large-uncased	24	1024	340M
BERT-Base	google-bert/bert-base-uncased	12	768	110M
BERT-Medium	google/bert_uncased_L-8_H-512_A-8	8	512	41.7M
BERT-Small	google/bert_uncased_L-4_H-512_A-8	4	512	29.1M
BERT-Mini	google/bert_uncased_L-4_H-256_A-4	4	256	11.3M
BERT-Tiny	google/bert_uncased_L-2_H-128_A-2	2	128

In [19]:
trainer = ModelTrainer(
    base_model="google/bert_uncased_L-2_H-128_A-2",
    dataset="guten_sentiment.csv",
    num_classes=10,
    max_len=128,
    output_dir="./bert_ordinal/medium",
    seed=1111
)

In [20]:
df = trainer.read_validate_data()
print(df.head())
trainer.tokenize_dataset()

Number of observations: 10889

Label distribution:
label
1      239
2      800
3     1436
4      821
5     4519
6      960
7      637
8      923
9      474
10      80
Name: count, dtype: int64
                                                text  label
0             In a moment they breathed more freely.      7
1  “I’m in favor of the eats part and that withou...      8
2  They even put preventer stays on the masts and...      5
3  “They’re merely telling one another what a nic...      7
4  It looks to me as if we’d never have another c...      8

Split sizes:
Train: 8711
Validation: 1089
Test: 1089

config.json:   0%|          | 0.00/382 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Map:   0%|          | 0/8711 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

Map:   0%|          | 0/1089 [00:00<?, ? examples/s]

(Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 8711
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }),
 Dataset({
     features: ['labels', 'input_ids', 'token_type_ids', 'attention_mask'],
     num_rows: 1089
 }))

In [21]:
trainer.train()

model.safetensors:   0%|          | 0.00/17.7M [00:00<?, ?B/s]

Some weights of BertForOrdinalRegression were not initialized from the model checkpoint at google/bert_uncased_L-2_H-128_A-2 and are newly initialized: ['first_threshold', 'sentiment_score.bias', 'sentiment_score.weight', 'threshold_deltas']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

early stopping required metric_for_best_model, but did not find eval_mae so early stopping is disabled

Test results:
test_loss: 1.2439402781385144e+28
test_mae: 1.3525456190109253
test_rmse: 1.8945732190704119
test_accuracy: 0.4150596877869605
test_within_1: 0.5785123966942148
test_quadratic_kappa: 0.0
test_spearman: 0.22589009078485497
test_runtime: 0.2198
test_samples_per_second: 4954.585
test_steps_per_second: 159.238
epoch: 3.0

TrainOutput(global_step=1635, training_loss=1.2444502134239928e+28, metrics={'train_runtime': 19.3413, 'train_samples_per_second': 1351.152, 'train_steps_per_second': 84.534, 'total_flos': 5366346987300.0, 'train_loss': 1.2444502134239928e+28, 'epoch': 3.0})

In [22]:
# Evaluate
results = trainer.test_results

print("Test MAE:", results["test_mae"])
print("Test RMSE:", results["test_rmse"])
print("Test Accuracy:", results["test_accuracy"])

Test MAE: 1.3525456190109253
Test RMSE: 1.8945732190704119
Test Accuracy: 0.4150596877869605

In [23]:
# Evaluate intermediate checkpoints
checkpoints = trainer.evaluate_interim_models()
print(checkpoints)

# Save best model
trainer.save_best_models(
    best_model_dir="./models/bert_ordinal_tiny_final"
)

                            checkpoint  step  is_best  validation_loss  \
0  bert_ordinal/medium/checkpoint-1200  1200    False     1.249852e+28
1  bert_ordinal/medium/checkpoint-1300  1300    False     1.249843e+28
2  bert_ordinal/medium/checkpoint-1400  1400    False     1.249836e+28
3  bert_ordinal/medium/checkpoint-1500  1500    False     1.249836e+28
4  bert_ordinal/medium/checkpoint-1600  1600     True     1.249836e+28
5  bert_ordinal/medium/checkpoint-1635  1635    False     1.249836e+28

   validation_model_preparation_time  validation_mae  validation_rmse  \
0                             0.0007        1.368981         1.899573
1                             0.0007        1.361924         1.898207
2                             0.0007        1.357707         1.897455
3                             0.0007        1.355839         1.897133
4                             0.0007        1.353774         1.896828
5                             0.0006        1.353699         1.896805

   validation_accuracy  validation_within_1  validation_quadratic_kappa  \
0              0.41506             0.578512                         0.0
1              0.41506             0.578512                         0.0
2              0.41506             0.578512                         0.0
3              0.41506             0.578512                         0.0
4              0.41506             0.578512                         0.0
5              0.41506             0.578512                         0.0

   validation_spearman  validation_runtime  validation_samples_per_second  \
0             0.116101              0.2154                       5055.778
1             0.123403              0.2169                       5021.788
2             0.133706              0.2292                       4750.422
3             0.129580              0.2156                       5050.445
4             0.129989              0.2115                       5149.913
5             0.133683              0.2126                       5121.687

   validation_steps_per_second
0                      162.491
1                      161.398
2                      152.677
3                      162.319
4                      165.516
5                      164.609

Model saved to: models/bert_ordinal_tiny_final

PosixPath('models/bert_ordinal_tiny_final')